### ISSUE TITLE
Seurat V5 compatibility issue

### ISSUE THREAD

**Issue by AMAwatermelon** [theMILOlab/SPATA2#94] opened 2023-11-30 06:33 UTC
Thank you for developing this useful tool! 
I had a problem creating an object submission using initiateSpataObject_10X and was told that the counts matrix could not be found. 
I assumed that a change in the data structure in seurat V5 was causing the problem, and after downgrading seurat to 4.4, it worked fine. In addition, when selecting a high resolution image using initiateSpataObject_10X, there is a problem with the resolution and alignment of the image. Thanks again for creating this wonderful tool and I hope you will check this out when you have time.

**Comment by acazelles** [comment] 2023-12-15 02:28
Hi,
I tried to downgrading seurat to 4.4 and reinstall SPATA2 but it didn't work. I cannot create new SPATA2 object.
I have this error : 
03:25:53 Starting initiation.
03:25:53 No gene-set data.frame path specified.
03:25:53 Reading in .h5 file.
03:25:53 Loading from directory: '/shared/ifbstor1/projects/vpj/Données_Visium/processed/Ech_405_A1/outs'
03:25:58 Performing Seurat-analysis steps.
03:25:58 Calculating percentage of ribosomal and mitochondrial genes.
03:25:58 Removing stress genes and mitochondrial genes.
Error in `LayerData()`:
! `features` must be a character vector, not a logical vector.
Run `rlang::last_trace()` to see where the error occurred.

Do you have a solution ?

Thanks for your help !

Antoine

**Comment by tsoruu** [comment] 2024-01-08 02:23
Hi, I have a problem with the same issue... The problem is that I've processed my data in Seurat v5 and was looking to do some trajectory analysis using SPATA2. The object I currently have is saved in RDS format and is in Seurat v5 format. Is there any workaround regarding this? Is there any way to downgrade the object to a lower version? I encounter a similar issue when trying to use CellTrek...

Thanks in advance and sorry for such inconvenience...

**Comment by acazelles** [comment] 2024-01-08 02:30
Hi,

Finally, I downgraded Seurat version using the 4.1.1. And it works to create a new spata_object.
And last week I had a new problem to create spata_object but I just had to update some packages.
I hope it will work for you !
Antoine

De : Sava Savero ***@***.***>
Date : dimanche, 7 janvier 2024 à 21:23
À : theMILOlab/SPATA2 ***@***.***>
Cc : acazelles ***@***.***>, Comment ***@***.***>
Objet : Re: [theMILOlab/SPATA2] Seurat V5 compatibility issue (Issue #94)

Hi, I have a problem with the same issue... The problem is that I've processed my data in Seurat v5 and was looking to do some trajectory analysis using SPATA2. The object I currently have is saved in RDS format and is in Seurat v5 format. Is there any workaround regarding this? Is there any way to downgrade the object to a lower version? I encounter a similar issue when trying to use CellTrek...

Thanks in advance and sorry for such inconvenience...

**Comment by tsoruu** [comment] 2024-01-09 07:16
Hi @acazelles! Thanks for the info! Anyway, I have an update regarding this. I'm able to create a SPATA object using Seurat v5.0.1 using the code found in https://github.com/satijalab/seurat/issues/7409#issuecomment-1584041598, but has a problem as all of the processed things that I've done in Seurat seems to be gone. I've got a problem processing my data in Seurat v4 for some reason and was wondering whether I could do it in v5, as it has succeeded. Downgrading Seurat seems kind of scary in my case as I'm afraid I couldn't access the processed RDS that is processed in v5...

**Comment by simonmfr** [comment] 2024-01-26 19:10
Hi all, please update both SPATA2 and Seurat (v5), the compatibility issue should be fixed.

**Closed** 2024-03-04 13:26 UTC
