### ISSUE TITLE
Error while running the runGSEA() function

### ISSUE THREAD

**Issue by dtonmoy** [theMILOlab/SPATA2#25] opened 2022-01-31 05:29 UTC
Hi,
I was trying the runGSEA() function mentioned [here](https://themilolab.github.io/SPATA2/articles/spata-v2-gsea.html) in the section 2. It seems the function should be runGSEA() instead of runGsea() mentioned in the website. Each time I run the function, I get some error. My command:

```
spata_obj <- runGSEA(object = spata_obj, 
                     across = "seurat_clusters",
                     methods_de = "wilcox")
```

Error message:
```
11:08:14 Using default gene set list.
11:10:58 Calculating enrichment of signatures across 'seurat_clusters' (n = 11). Based on results of method 'wilcox'.
11:10:58 Working on group: '0' (1/11)
Error in FUN(X[[i]], ...) : 
  cannot coerce type 'closure' to vector of type 'character'

```

Can you please check it out and let me know what might be the problem here?

**Comment by kueckelj** [comment] 2022-01-31 10:12
Hi dtonmoy, 
unfortunately I can not reproduce the error. I am aware of it thoug as I am recieving this error message, too, from time to time. However, I haven't figured out yet what actually causes the problem because sometimes it works and sometimes it does not. I Could you try it with a different sample as well as with different de methods? And tell me what does work and what doesn't? 

I'll have a deeper look into it now.

(You are right about the naming issue. Thanks for mentioning it. I've changed the function name after generating the HTML file for the tutorial. I'll upload the option to use `runGsea()`.)

**Comment by kueckelj** [comment] 2022-01-31 10:22
To accelerate the process I've created a new branch in SPATA2. Could you install this one with `devtools::install_github("theMILOlab/SPATA2", "runGSEA_debug")` ? Once you've done that runGSEA() should print out additional messages regarding the computational steps (Step 1, Step 2, Step 3 etc.). Could you run the function again and tell me after which step the function throws the error message? 

I need your help with this one as I can not reproduce the error with my spatial transcriptomic samples.

**Comment by dtonmoy** [comment] 2022-01-31 11:17
Hi Jan,
It seems the problem is in the Step 1. Error message:

```
16:45:04 Using default gene set list.
16:47:53 Calculating enrichment of signatures across 'seurat_clusters' (n = 6). Based on results of method 'wilcox'.
16:47:53 Working on group: '0' (1/6)
Step 1
Error in FUN(X[[i]], ...) : 
  cannot coerce type 'closure' to vector of type 'character'
```

I have tried running the function on three of my samples as well as with different de methods. However, same error is occurring each of the time.

**Comment by kueckelj** [comment] 2022-01-31 11:21
Okay. This means that the error is thrown within the function hypeR::hypeR(). I'll talk to the developers of the package what exactly the problem might be. I come back to you once I know more.

**Comment by kueckelj** [comment] 2022-01-31 12:03
The function runGSEA() takes an argument called 'quiet'. Could you set it to FALSE and run the function again. Does it print any information or does it crash beforehand?

**Comment by dtonmoy** [comment] 2022-01-31 12:21
Here is the output:

```
18:12:04 Using default gene set list.
18:14:41 Calculating enrichment of signatures across 'seurat_clusters' (n = 6). Based on results of method 'wilcox'.
18:14:41 Working on group: '0' (1/6)
Step 1
Signature size: 50
Number of genesets: 11657
Percentage of signature found across genesets: 0.98% 
Background population size: 19646 
P-Value cutoff: 1 
FDR cutoff: 1
Error in FUN(X[[i]], ...) : 
  cannot coerce type 'closure' to vector of type 'character'
In addition: Warning messages:
1: In initialize(...) :
  Describing genesets with a name will aid reproducibility
2: In initialize(...) :
  Including a version number will aid reproducibility
```

**Comment by kueckelj** [comment] 2022-01-31 13:22
I have changed the code. Can you reinstall the debug branch and check if it works now?

**Comment by dtonmoy** [comment] 2022-01-31 13:53
Wow!! It's working perfectly fine now!!

**Comment by kueckelj** [comment] 2022-01-31 14:13
Great. I've merged the branch and deleted the debugging branch. It would be best if you switch back to the master branch by installing it. The function is fixed there and should work.

**Comment by kueckelj** [comment] 2022-01-31 14:14
Let me know if the function works there. Then I'll close this issue.

**Comment by dtonmoy** [comment] 2022-01-31 14:56
The master branch is working perfectly. Thank you so much!!!

**Comment by kueckelj** [comment] 2022-01-31 17:19
Great!

**Closed by kueckelj** 2022-01-31 17:19 UTC
